---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - '**/*.rb'
  Exclude:
    - '_snippets/**/*'  # Demo files for instruction
    - 'repostore/**/*'  # CodePraise cloned code repos

require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sequel

# Ignore block length where unavoidable (e.g., frameworks using blocks)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - Rakefile
    - app/application/controllers/**/*.rb # Roda's nested controllers require large blocks
    - spec/**/* # Minitest's nested test structure requires large blocks
    - Rakefile # Rake namespaces produce large blocks

# See: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/MultilineMethodCallIndentation
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - Rakefile

Naming/RescuedExceptionsVariableName:
  Enabled: false
