---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore

test:
  DB_FILENAME: db/local/test.db
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore

production:
  # Assign DATABASE_URL in production
  GITHUB_TOKEN: create_github_token
  REPOSTORE_PATH: repostore